[package]
name = "bgpkit_parser_py"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
bgpkit-parser = { git = "https://github.com/bgpkit/bgpkit-parser", branch = "main" }
pyo3 = { version = "0.20", features = ["extension-module"] }
